/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormMDI.java
 *
 * Created on 20/10/2009, 20:03:25
 */

package br.fatecpg.principal;


import br.fatecpg.corretor.FormCadastroCorretor;
import javax.swing.JFrame;

/**
 *
 * @author okada
 */
public class FormMDI extends javax.swing.JFrame {

    FormCadastroCorretor formCadCorretor;



    public FormMDI() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMDIPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        subMenuCadastroComprador = new javax.swing.JMenuItem();
        subMenuCadastroCorretor = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        subMenuCadastroComprador.setText("Comprador");
        subMenuCadastroComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroCompradorActionPerformed(evt);
            }
        });
        menuCadastro.add(subMenuCadastroComprador);

        subMenuCadastroCorretor.setText("Corretor");
        subMenuCadastroCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroCorretorActionPerformed(evt);
            }
        });
        menuCadastro.add(subMenuCadastroCorretor);

        jMenuBar1.add(menuCadastro);

        jMenu1.setText("Manutenção");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ferramentas");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Sair");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMDIPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMDIPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    


    private void subMenuCadastroCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroCompradorActionPerformed
        //tenho q chamar mostraCadastroComprador
        //para abrir o form na area de trab do programa
       
    }//GEN-LAST:event_subMenuCadastroCompradorActionPerformed

    private void abreFormCadastroCorretor(){

    if(formCadCorretor == null){

        formCadCorretor = new FormCadastroCorretor();
        panelMDIPrincipal.add(formCadCorretor);
        formCadCorretor.setVisible(true);

    }else{


        formCadCorretor.setVisible(true);



    }


    }

    private void subMenuCadastroCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroCorretorActionPerformed
        abreFormCadastroCorretor();
    }//GEN-LAST:event_subMenuCadastroCorretorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JDesktopPane panelMDIPrincipal;
    private javax.swing.JMenuItem subMenuCadastroComprador;
    private javax.swing.JMenuItem subMenuCadastroCorretor;
    // End of variables declaration//GEN-END:variables

}
