/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormTemplate.java
 *
 * Created on 20/10/2009, 19:58:39
 */

package br.fatecpg.comprador;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author okada
 */
public class FormManutencaoComprador extends javax.swing.JInternalFrame {
    
    /** Creates new form FormTemplate */
    public FormManutencaoComprador() {
        initComponents();
        listaComprador();
    }

    DefaultTableModel tmComprador = new DefaultTableModel(null,new String[]{"Código","Nome","Endereço","Telefone"});
    ListSelectionModel lsmComprador;
    List<BeanComprador> comprador;

    private int cdComprador;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manutencaoCompradorPanelComponentes = new javax.swing.JPanel();
        tabelaCompradorPanel = new javax.swing.JScrollPane();
        tabelaComprador = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nomeCompradorLabel = new javax.swing.JLabel();
        nomeCompradorField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataCadastroCompradorField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoLogradouroCompradorField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        logradouroCompradorField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numeroLogradouroCompradorField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bairroCompradorField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cidadeCompradorField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ufCompradorField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dddTelefoneCompradorField = new javax.swing.JTextField();
        telefoneCompradorField = new javax.swing.JTextField();
        manutencaoCompradorPanelBotoes = new javax.swing.JPanel();
        selecionarCompradorButton = new javax.swing.JButton();
        excluirCompradorButton = new javax.swing.JButton();
        atualizarCompradorButton = new javax.swing.JButton();
        cancelarCompradorButton = new javax.swing.JButton();
        sairCompradorButton = new javax.swing.JButton();

        setTitle("Manutenção de Compradores");

        manutencaoCompradorPanelComponentes.setBackground(new java.awt.Color(173, 190, 206));
        manutencaoCompradorPanelComponentes.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tabelaComprador.setModel(tmComprador);
        tabelaComprador.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmComprador = tabelaComprador.getSelectionModel();
        lsmComprador.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e){

                if(!e.getValueIsAdjusting()){

                    tbCompradorLinhaSelecionada(tabelaComprador);

                }

            }

        });
        tabelaCompradorPanel.setViewportView(tabelaComprador);

        jPanel1.setBackground(new java.awt.Color(173, 190, 206));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        nomeCompradorLabel.setText("Nome");

        jLabel2.setText("Data Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCompradorLabel)
                    .addComponent(nomeCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dataCadastroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompradorLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataCadastroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(173, 190, 206));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel1.setText("Tipo Logradouro");

        jLabel3.setText("Logradouro");

        jLabel4.setText("Número");

        jLabel5.setText("Bairro");

        jLabel6.setText("Cidade");

        jLabel7.setText("UF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipoLogradouroCompradorField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(logradouroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(numeroLogradouroCompradorField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(ufCompradorField))
                                .addGap(55, 55, 55))))
                    .addComponent(bairroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(211, 211, 211)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLogradouroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logradouroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroLogradouroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(173, 190, 206));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        jLabel8.setText("DDD");

        jLabel9.setText("Telefone");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dddTelefoneCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefoneCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(481, 481, 481))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dddTelefoneCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneCompradorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout manutencaoCompradorPanelComponentesLayout = new javax.swing.GroupLayout(manutencaoCompradorPanelComponentes);
        manutencaoCompradorPanelComponentes.setLayout(manutencaoCompradorPanelComponentesLayout);
        manutencaoCompradorPanelComponentesLayout.setHorizontalGroup(
            manutencaoCompradorPanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manutencaoCompradorPanelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manutencaoCompradorPanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelaCompradorPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE))
                .addContainerGap())
        );
        manutencaoCompradorPanelComponentesLayout.setVerticalGroup(
            manutencaoCompradorPanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manutencaoCompradorPanelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaCompradorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        manutencaoCompradorPanelBotoes.setBackground(new java.awt.Color(173, 190, 206));
        manutencaoCompradorPanelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        selecionarCompradorButton.setText("Selecionar");
        selecionarCompradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarCompradorButtonActionPerformed(evt);
            }
        });

        excluirCompradorButton.setText("Excluir");

        atualizarCompradorButton.setText("Atualizar");

        cancelarCompradorButton.setText("Cancelar");

        sairCompradorButton.setText("Sair");
        sairCompradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairCompradorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manutencaoCompradorPanelBotoesLayout = new javax.swing.GroupLayout(manutencaoCompradorPanelBotoes);
        manutencaoCompradorPanelBotoes.setLayout(manutencaoCompradorPanelBotoesLayout);
        manutencaoCompradorPanelBotoesLayout.setHorizontalGroup(
            manutencaoCompradorPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manutencaoCompradorPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecionarCompradorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirCompradorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atualizarCompradorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarCompradorButton)
                .addGap(57, 57, 57)
                .addComponent(sairCompradorButton)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        manutencaoCompradorPanelBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {atualizarCompradorButton, cancelarCompradorButton, excluirCompradorButton, sairCompradorButton, selecionarCompradorButton});

        manutencaoCompradorPanelBotoesLayout.setVerticalGroup(
            manutencaoCompradorPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manutencaoCompradorPanelBotoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(manutencaoCompradorPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarCompradorButton)
                    .addComponent(excluirCompradorButton)
                    .addComponent(atualizarCompradorButton)
                    .addComponent(cancelarCompradorButton)
                    .addComponent(sairCompradorButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manutencaoCompradorPanelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manutencaoCompradorPanelComponentes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manutencaoCompradorPanelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manutencaoCompradorPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-795)/2, (screenSize.height-683)/2, 795, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void listaComprador(){

    ControlComprador crtComp = new ControlComprador();
    comprador = crtComp.listaComprador();
    mostraComprador(comprador);

    }

    private void mostraComprador(List<BeanComprador> ls){

        try {



    if(ls.size() == 0){

        JOptionPane.showMessageDialog(null,"Não existe registros na tabela Comprador");

    }else{

    while(tmComprador.getRowCount()>0){

        tmComprador.removeRow(0);

        }
        
    String [] campos = new String[]{null,null,null,null};

    for(int i=0;i<=ls.size();i++){

        tmComprador.addRow(campos);
        tmComprador.setValueAt(ls.get(i).getCd_comprador(), i, 0);
        tmComprador.setValueAt(ls.get(i).getNm_comprador(), i, 1);
        tmComprador.setValueAt(ls.get(i).getNm_logradouro(), i, 2);
        tmComprador.setValueAt(ls.get(i).getCd_telefone(), i, 3);


    }

    }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Erro com o método mostraComprador : "+e);

        }
    }


    private void tbCompradorLinhaSelecionada(JTable jt){

    if(jt.getSelectedRow()!=-1){

    this.nomeCompradorField.setText(comprador.get(jt.getSelectedRow()).getNm_comprador());
    this.dataCadastroCompradorField.setText(comprador.get(jt.getSelectedRow()).getDt_cadastro());
    this.tipoLogradouroCompradorField.setText(comprador.get(jt.getSelectedRow()).getNm_tipo_logradouro());
    this.logradouroCompradorField.setText(comprador.get(jt.getSelectedRow()).getNm_logradouro());
    this.numeroLogradouroCompradorField.setText(comprador.get(jt.getSelectedRow()).getQt_numero_logradouro());
    this.bairroCompradorField.setText(comprador.get(jt.getSelectedRow()).getNm_bairro());
    this.cidadeCompradorField.setText(comprador.get(jt.getSelectedRow()).getNm_cidade());
    this.ufCompradorField.setText(comprador.get(jt.getSelectedRow()).getSg_unidade_federativa());
    this.dddTelefoneCompradorField.setText(comprador.get(jt.getSelectedRow()).getCd_ddd_telefone());
    this.telefoneCompradorField.setText(comprador.get(jt.getSelectedRow()).getCd_telefone());
    
    this.cdComprador = comprador.get(jt.getSelectedRow()).getCd_comprador();

    }



    };


    private void atualizaDadosComprador(){

    BeanComprador bc = new BeanComprador();
    ControlComprador cComp = new ControlComprador();

    bc.setCd_comprador(cdComprador);
    bc.setNm_comprador(this.nomeCompradorField.getText().toUpperCase().trim());
    bc.setDt_cadastro(this.dataCadastroCompradorField.getText().trim());






    }



    private void sair(){

    

    }

    private void sairCompradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairCompradorButtonActionPerformed
        sair();
}//GEN-LAST:event_sairCompradorButtonActionPerformed

    private void selecionarCompradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarCompradorButtonActionPerformed
        tbCompradorLinhaSelecionada(tabelaComprador);
    }//GEN-LAST:event_selecionarCompradorButtonActionPerformed
    




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarCompradorButton;
    private javax.swing.JTextField bairroCompradorField;
    private javax.swing.JButton cancelarCompradorButton;
    private javax.swing.JTextField cidadeCompradorField;
    private javax.swing.JTextField dataCadastroCompradorField;
    private javax.swing.JTextField dddTelefoneCompradorField;
    private javax.swing.JButton excluirCompradorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField logradouroCompradorField;
    private javax.swing.JPanel manutencaoCompradorPanelBotoes;
    private javax.swing.JPanel manutencaoCompradorPanelComponentes;
    private javax.swing.JTextField nomeCompradorField;
    private javax.swing.JLabel nomeCompradorLabel;
    private javax.swing.JTextField numeroLogradouroCompradorField;
    private javax.swing.JButton sairCompradorButton;
    private javax.swing.JButton selecionarCompradorButton;
    private javax.swing.JTable tabelaComprador;
    private javax.swing.JScrollPane tabelaCompradorPanel;
    private javax.swing.JTextField telefoneCompradorField;
    private javax.swing.JTextField tipoLogradouroCompradorField;
    private javax.swing.JTextField ufCompradorField;
    // End of variables declaration//GEN-END:variables
    
}
